# Site Settings
baseurl: "/"
url : "https://mirutree.github.io"

# Blog Settings
theme_settings :
  title : Mirutree's BLOG
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/mimo.png
    username : Mirutree
    description : "It's not open yet"
    experience :
      - start : 2021-01-20
        end : 
        experience : company name, title
    skills : 
      - skill : HTML5 & CSS
        value : 85  # Percent value
        
  # Icons
  icons :
    email:  # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: mirutree
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
